const { SCLogicMgr2 } = require("./logicmgr2.js");
const { parseSlotCraftJson } = require("./utils.js");

test("logic test 002", async () => {
    const logic = new SCLogicMgr2();

    const statedata = {
        "bg-spin": {
            list: ["bg-spin", "bg-cashweight"],
            module: "SpinModule",
            performance: "",
        },
        "bg-wildex": {
            list: ["bg-replace"],
            module: "SymChangeModule",
            performance: "",
        },
        "bg-solar": {
            list: ["bg-cashwin"],
            module: "SymCollectCoinModule",
            performance: "",
        },
        "bg-win": {
            list: ["bg-win"],
            module: "ShowTopModule",
            performance: "",
        },
        "bg-win2": {
            list: ["bg-win"],
            module: "WinAniModule",
            performance: "",
        },
        "fg-start": {
            list: ["bg-triggerfg"],
            module: "FgModule",
            performance: "",
        },
        "fg-spin": {
            list: ["fg-spin"],
            module: "SymChangeModule",
            performance: "",
        },
        "fg-end": {
            list: ["fg-start"],
            module: "FgExitModule",
            performance: "",
            bquick: false,
            toui: true,
            exitmodule: "FgExitModule",
        },
    };
    const statelist = [
        "bg-spin",
        "bg-wildex",
        "bg-solar",
        "bg-win",
        "bg-win2",
        "fg-start",
        "fg-spin",
        "fg-end",
    ];

    const gamecfg = {
        50: {
            mapComponents: {
                "fg-jackpot1": {
                    config: {
                        defaultNextComponent: "fg-triggerjackpot2",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "jackpot",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        betType: "bet",
                        wins: 2500,
                        winMulti: 0,
                    },
                },
                "fg-triggerjackpot0": {
                    config: {
                        defaultNextComponent: "fg-triggerjackpot1",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-jackpot0",
                    },
                },
                "bg-replace": {
                    config: {
                        defaultNextComponent: "bg-solartrigger",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "replaceReelWithMask",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbol: "WL",
                        mask: "bg-wildexmask",
                        ignoreSymbols: ["SC"],
                    },
                },
                "fg-rollnum1": {
                    config: {
                        defaultNextComponent: "fg-mul1",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "rollNumber",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        weight: "cashmutiweights",
                        awards: [
                            {
                                awardType: "chgComponentConfigIntVal",
                                vals: null,
                                strParams: ["fg-mul1.multi"],
                                componentVals: ["fg-rollnum1.outputInt"],
                                onTriggerRespin: "",
                            },
                        ],
                    },
                },
                "fg-spin": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "chgSymbols",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        chgSymbolsType: "normal",
                        symbols: [
                            "WL",
                            "A",
                            "B",
                            "C",
                            "D",
                            "E",
                            "F",
                            "G",
                            "BN",
                        ],
                        blankSymbol: "BN",
                        weight: "changeweights",
                        maxNumber: 0,
                        isAlwaysGen: true,
                        controllers: [
                            {
                                awardType: "setComponentConfigIntVal",
                                vals: [3],
                                strParams: ["fg-start.lastTriggerNum"],
                                componentVals: null,
                                onTriggerRespin: "",
                            },
                        ],
                        jumpToComponent: "fg-cashweight",
                    },
                },
                "bg-solartrigger": {
                    config: {
                        defaultNextComponent: "bg-win",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "scatterTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbols: ["SC"],
                        type: "countscatterReels",
                        betType: "noPay",
                        symbolValsMulti: "",
                        minNum: 1,
                        wildSymbols: null,
                        posArea: null,
                        countScatterPayAs: "",
                        winMulti: 1,
                        jumpToComponent: "bg-solarmask",
                        piggyBankComponent: "",
                        forceToNext: false,
                        awards: null,
                        symbolAwardsWeights: null,
                        targetMask: "",
                        isReverse: false,
                        isAddRespinMode: false,
                        respinComponent: "",
                        respinNum: 0,
                        respinNumWeight: "",
                        respinNumWithScatterNum: null,
                        respinNumWeightWithScatterNum: null,
                    },
                },
                "bg-solarmask": {
                    config: {
                        defaultNextComponent: "bg-solarweights",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "mask",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        num: 5,
                        perMaskAwards: null,
                        mapSPMaskAwards: null,
                    },
                },
                "bg-cashweight": {
                    config: {
                        defaultNextComponent: "bg-wildex",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "genSymbolValsWithSymbol",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "normal",
                        symbols: ["SC"],
                        weight: "cashweights",
                        defaultVal: 0,
                        isUseSource: true,
                        isAlwaysGen: true,
                    },
                },
                "fg-rollnum0": {
                    config: {
                        defaultNextComponent: "fg-mul0",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "rollNumber",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        weight: "cashmutiweights",
                        awards: [
                            {
                                awardType: "chgComponentConfigIntVal",
                                vals: null,
                                strParams: ["fg-mul0.multi"],
                                componentVals: ["fg-rollnum0.outputInt"],
                                onTriggerRespin: "",
                            },
                        ],
                    },
                },
                "fg-jackpot0": {
                    config: {
                        defaultNextComponent: "fg-triggerjackpot1",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "jackpot",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        betType: "bet",
                        wins: 500,
                        winMulti: 0,
                    },
                },
                "fg-triggerjackpot1": {
                    config: {
                        defaultNextComponent: "fg-triggerjackpot2",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-jackpot1",
                    },
                },
                "fg-column1": {
                    config: {
                        defaultNextComponent: "fg-column2",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-rollnum1",
                    },
                },
                "fg-rollnum3": {
                    config: {
                        defaultNextComponent: "fg-mul3",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "rollNumber",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        weight: "cashmutiweights",
                        awards: [
                            {
                                awardType: "chgComponentConfigIntVal",
                                vals: null,
                                strParams: ["fg-mul3.multi"],
                                componentVals: ["fg-rollnum3.outputInt"],
                                onTriggerRespin: "",
                            },
                        ],
                    },
                },
                "bg-cashwin": {
                    config: {
                        defaultNextComponent: "bg-win",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "symbolValWins",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        betType: "bet",
                        winMulti: 1,
                        symbols: null,
                        type: "normal",
                    },
                },
                "fg-start": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "respin",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        mainComponent: "fg-spin",
                    },
                },
                "fg-cashweight": {
                    config: {
                        defaultNextComponent: "fg-checkcol",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "genSymbolValsWithSymbol",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "normal",
                        symbols: ["SC"],
                        weight: "cashweights",
                        defaultVal: 0,
                        isUseSource: true,
                        isAlwaysGen: true,
                    },
                },
                "fg-checkrow": {
                    config: {
                        defaultNextComponent: "fg-column0",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "reelTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbol: "SC",
                        type: "row",
                        wildSymbols: null,
                        minSymbolNum: 5,
                        targetMask: "",
                        mapBranchs: {
                            4: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-column3.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                            1: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-column0.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                            2: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-column1.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                            3: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-column2.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                        },
                    },
                },
                "fg-mul1": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "chgSymbolVals",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "mul",
                        sourceType: "row",
                        positionCollection: "",
                        winResultComponents: null,
                        maxNumber: 0,
                        maxVal: 999999,
                        minVal: 0,
                        row: 1,
                        column: 0,
                        multi: 1,
                    },
                },
                "fg-mul2": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "chgSymbolVals",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "mul",
                        sourceType: "row",
                        positionCollection: "",
                        winResultComponents: null,
                        maxNumber: 0,
                        maxVal: 999999,
                        minVal: 0,
                        row: 2,
                        column: 0,
                        multi: 1,
                    },
                },
                "bg-solarweights": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "weightBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        forceBranch: "",
                        weight: "solarweights",
                        mapBranchs: {
                            solar: {
                                awards: null,
                                jumpToComponent: "bg-cashwin",
                            },
                            normal: { awards: null, jumpToComponent: "bg-win" },
                        },
                    },
                },
                "bg-wildex": {
                    config: {
                        defaultNextComponent: "bg-solartrigger",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "scatterTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbols: ["WL"],
                        type: "countscatterReels",
                        betType: "bet",
                        symbolValsMulti: "",
                        minNum: 1,
                        wildSymbols: [],
                        posArea: null,
                        countScatterPayAs: "WL",
                        winMulti: 1,
                        jumpToComponent: "bg-wildexmask",
                        piggyBankComponent: "",
                        forceToNext: false,
                        awards: [],
                        symbolAwardsWeights: null,
                        targetMask: "bg-wildexmask",
                        isReverse: false,
                        isAddRespinMode: false,
                        respinComponent: "",
                        respinNum: 3,
                        respinNumWeight: "",
                        respinNumWithScatterNum: null,
                        respinNumWeightWithScatterNum: null,
                    },
                },
                "fg-column2": {
                    config: {
                        defaultNextComponent: "fg-column3",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-rollnum2",
                    },
                },
                "fg-mul3": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "chgSymbolVals",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "mul",
                        sourceType: "row",
                        positionCollection: "",
                        winResultComponents: null,
                        maxNumber: 0,
                        maxVal: 999999,
                        minVal: 0,
                        row: 3,
                        column: 0,
                        multi: 1,
                    },
                },
                "fg-triggerjackpot2": {
                    config: {
                        defaultNextComponent: "fg-checkrow",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-jackpot2",
                    },
                },
                "bg-win": {
                    config: {
                        defaultNextComponent: "bg-triggerfg",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "linesTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbols: ["A", "B", "C", "D", "E", "F", "G"],
                        type: "lines",
                        betType: "bet",
                        symbolValsMulti: "",
                        minNum: 0,
                        wildSymbols: ["WL"],
                        checkWinType: "left2right",
                        winMulti: 1,
                        jumpToComponent: "",
                        forceToNext: false,
                        awards: null,
                        symbolAwardsWeights: null,
                        targetMask: "",
                        isReverse: false,
                        piggyBankComponent: "",
                        isAddRespinMode: false,
                        respinNum: 0,
                        respinNumWeight: "",
                        respinNumWithScatterNum: null,
                        respinNumWeightWithScatterNum: null,
                    },
                },
                "bg-wildexmask": {
                    config: {
                        defaultNextComponent: "bg-replace",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "mask",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        num: 5,
                        perMaskAwards: null,
                        mapSPMaskAwards: null,
                    },
                },
                "bg-triggerfg": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "scatterTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbols: ["SC"],
                        type: "countscatter",
                        betType: "noPay",
                        symbolValsMulti: "",
                        minNum: 5,
                        wildSymbols: null,
                        posArea: null,
                        countScatterPayAs: "",
                        winMulti: 1,
                        jumpToComponent: "fg-start",
                        piggyBankComponent: "",
                        forceToNext: false,
                        awards: [
                            {
                                awardType: "setComponentConfigIntVal",
                                vals: [3],
                                strParams: ["fg-start.lastRespinNum"],
                                componentVals: null,
                                onTriggerRespin: "",
                            },
                        ],
                        symbolAwardsWeights: null,
                        targetMask: "",
                        isReverse: false,
                        isAddRespinMode: false,
                        respinComponent: "",
                        respinNum: 3,
                        respinNumWeight: "",
                        respinNumWithScatterNum: null,
                        respinNumWeightWithScatterNum: null,
                    },
                },
                "fg-checkcol": {
                    config: {
                        defaultNextComponent: "fg-triggerjackpot0",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "reelTrigger",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        symbol: "SC",
                        type: "columnNumber",
                        wildSymbols: null,
                        minSymbolNum: 4,
                        targetMask: "",
                        mapBranchs: {
                            4: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-triggerjackpot1.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                            5: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-triggerjackpot2.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                            3: {
                                awards: [
                                    {
                                        awardType: "chgComponentConfigIntVal",
                                        vals: [1],
                                        strParams: ["fg-triggerjackpot0.queue"],
                                        componentVals: null,
                                        onTriggerRespin: "",
                                    },
                                ],
                                jumpToComponent: "",
                            },
                        },
                    },
                },
                "fg-jackpot2": {
                    config: {
                        defaultNextComponent: "fg-checkrow",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "jackpot",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        betType: "bet",
                        wins: 500000,
                        winMulti: 0,
                    },
                },
                "fg-column0": {
                    config: {
                        defaultNextComponent: "fg-column1",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-rollnum0",
                    },
                },
                "fg-mul0": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "chgSymbolVals",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        type: "mul",
                        sourceType: "row",
                        positionCollection: "",
                        winResultComponents: null,
                        maxNumber: 0,
                        maxVal: 999999,
                        minVal: 0,
                        row: 0,
                        column: 0,
                        multi: 1,
                    },
                },
                "bg-spin": {
                    config: {
                        defaultNextComponent: "bg-cashweight",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "basicReels",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        reelSet: "reel0",
                        isExpandReel: false,
                        awards: null,
                    },
                },
                "fg-column3": {
                    config: {
                        defaultNextComponent: "",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "queueBranch",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        jumpToComponent: "fg-rollnum3",
                    },
                },
                "fg-rollnum2": {
                    config: {
                        defaultNextComponent: "fg-mul2",
                        tagRNG: null,
                        initStrVals: null,
                        useFileMapping: false,
                        componentType: "rollNumber",
                        targetScenes3: null,
                        targetOtherScenes3: null,
                        weight: "cashmutiweights",
                        awards: [
                            {
                                awardType: "chgComponentConfigIntVal",
                                vals: null,
                                strParams: ["fg-mul2.multi"],
                                componentVals: ["fg-rollnum2.outputInt"],
                                onTriggerRespin: "",
                            },
                        ],
                    },
                },
            },
            Stats2: null,
        },
    };
    const msg = {
        msgid: "gamemoduleinfo",
        gamemodulename: "solarreels",
        gameid: 61143,
        gmi: {
            defaultScene: {
                values: [
                    {
                        values: [1, 2, 3, 4],
                    },
                    {
                        values: [5, 6, 7, 8],
                    },
                    {
                        values: [2, 3, 4, 5],
                    },
                    {
                        values: [3, 4, 5, 6],
                    },
                    {
                        values: [4, 5, 6, 7],
                    },
                ],
                indexes: [],
                validRow: [],
            },
            replyPlay: {
                randomNumbers: [7, 93, 29, 16, 56, 730, 19],
                results: [
                    {
                        coinWin: 15,
                        cashWin: 1500,
                        clientData: {
                            scenes: [
                                {
                                    values: [
                                        {
                                            values: [8, 7, 5, 5],
                                        },
                                        {
                                            values: [2, 5, 5, 4],
                                        },
                                        {
                                            values: [7, 7, 5, 3],
                                        },
                                        {
                                            values: [6, 7, 4, 7],
                                        },
                                        {
                                            values: [1, 7, 6, 6],
                                        },
                                    ],
                                    indexes: [],
                                    validRow: [],
                                },
                            ],
                            otherScenes: [
                                {
                                    values: [
                                        {
                                            values: [150, 0, 0, 0],
                                        },
                                        {
                                            values: [0, 0, 0, 0],
                                        },
                                        {
                                            values: [0, 0, 0, 0],
                                        },
                                        {
                                            values: [0, 0, 0, 0],
                                        },
                                        {
                                            values: [0, 0, 0, 0],
                                        },
                                    ],
                                    indexes: [],
                                    validRow: [],
                                },
                            ],
                            results: [
                                {
                                    pos: [0, 0],
                                    type: 5,
                                    lineIndex: -1,
                                    symbol: 8,
                                    mul: 0,
                                    coinWin: 0,
                                    cashWin: 0,
                                    otherMul: 0,
                                    wilds: 0,
                                    symbolNums: 1,
                                    value: 0,
                                },
                                {
                                    pos: [0, 2, 1, 2, 2, 2],
                                    type: 2,
                                    lineIndex: 2,
                                    symbol: 5,
                                    mul: 5,
                                    coinWin: 5,
                                    cashWin: 500,
                                    otherMul: 1,
                                    wilds: 0,
                                    symbolNums: 3,
                                    value: 0,
                                },
                                {
                                    pos: [0, 2, 1, 1, 2, 2],
                                    type: 2,
                                    lineIndex: 11,
                                    symbol: 5,
                                    mul: 5,
                                    coinWin: 5,
                                    cashWin: 500,
                                    otherMul: 1,
                                    wilds: 0,
                                    symbolNums: 3,
                                    value: 0,
                                },
                                {
                                    pos: [0, 3, 1, 2, 2, 2],
                                    type: 2,
                                    lineIndex: 19,
                                    symbol: 5,
                                    mul: 5,
                                    coinWin: 5,
                                    cashWin: 500,
                                    otherMul: 1,
                                    wilds: 0,
                                    symbolNums: 3,
                                    value: 0,
                                },
                            ],
                            mulPos: [],
                            prizeScenes: [],
                            curGameMod: "basic",
                            curGameModParam: {
                                historyComponents: [
                                    "bg-spin",
                                    "bg-cashweight",
                                    "bg-solartrigger",
                                    "bg-solarmask",
                                    "bg-solarweights",
                                    "bg-win",
                                ],
                                respinComponents: [],
                                mapComponents: {
                                    "bg-spin": {
                                        basicComponentData: {
                                            usedScenes: [0],
                                            usedOtherScenes: [],
                                            usedResults: [],
                                            usedPrizeScenes: [],
                                            srcScenes: [],
                                            coinWin: 0,
                                            cashWin: 0,
                                            targetScene: 0,
                                            runIndex: 0,
                                            output: 0,
                                            strOutput: "",
                                        },
                                        "@type":
                                            "type.googleapis.com/sgc7pb.BasicComponentData",
                                    },
                                    "bg-cashweight": {
                                        basicComponentData: {
                                            usedScenes: [],
                                            usedOtherScenes: [0],
                                            usedResults: [],
                                            usedPrizeScenes: [],
                                            srcScenes: [0],
                                            coinWin: 0,
                                            cashWin: 0,
                                            targetScene: 0,
                                            runIndex: 0,
                                            output: 0,
                                            strOutput: "",
                                        },
                                        "@type":
                                            "type.googleapis.com/sgc7pb.BasicComponentData",
                                    },
                                    "bg-solartrigger": {
                                        basicComponentData: {
                                            usedScenes: [],
                                            usedOtherScenes: [],
                                            usedResults: [0],
                                            usedPrizeScenes: [],
                                            srcScenes: [],
                                            coinWin: 0,
                                            cashWin: 0,
                                            targetScene: 0,
                                            runIndex: 0,
                                            output: 0,
                                            strOutput: "",
                                        },
                                        nextComponent: "bg-solarmask",
                                        symbolNum: 1,
                                        wildNum: 0,
                                        respinNum: 0,
                                        wins: 0,
                                        winMulti: 1,
                                        "@type":
                                            "type.googleapis.com/sgc7pb.ScatterTriggerData",
                                    },
                                    "bg-solarmask": {
                                        vals: [
                                            false,
                                            false,
                                            false,
                                            false,
                                            false,
                                        ],
                                        newVals: [
                                            false,
                                            false,
                                            false,
                                            false,
                                            false,
                                        ],
                                        basicComponentData: null,
                                        num: 5,
                                        newChged: 0,
                                        "@type":
                                            "type.googleapis.com/sgc7pb.MaskData",
                                    },
                                    "bg-solarweights": {
                                        basicComponentData: {
                                            usedScenes: [],
                                            usedOtherScenes: [],
                                            usedResults: [],
                                            usedPrizeScenes: [],
                                            srcScenes: [],
                                            coinWin: 0,
                                            cashWin: 0,
                                            targetScene: 0,
                                            runIndex: 0,
                                            output: 0,
                                            strOutput: "",
                                        },
                                        value: "normal",
                                        "@type":
                                            "type.googleapis.com/sgc7pb.WeightBranchData",
                                    },
                                    "bg-win": {
                                        basicComponentData: {
                                            usedScenes: [],
                                            usedOtherScenes: [],
                                            usedResults: [1, 2, 3],
                                            usedPrizeScenes: [],
                                            srcScenes: [],
                                            coinWin: 15,
                                            cashWin: 1500,
                                            targetScene: 0,
                                            runIndex: 0,
                                            output: 0,
                                            strOutput: "",
                                        },
                                        nextComponent: "",
                                        symbolNum: 9,
                                        wildNum: 0,
                                        respinNum: 0,
                                        wins: 15,
                                        winMulti: 1,
                                        "@type":
                                            "type.googleapis.com/sgc7pb.LinesTriggerData",
                                    },
                                },
                                mapVals: {
                                    1: 5,
                                    2: 4,
                                    6: 50,
                                    7: 0,
                                },
                                mapStrVals: {},
                                firstComponent: "",
                                nextStepFirstComponent: "",
                                "@type": "type.googleapis.com/sgc7pb.GameParam",
                            },
                            nextGameMod: "basic",
                            curIndex: 0,
                            parentIndex: 0,
                            modType: "",
                            prizeCoinWin: 0,
                            prizeCashWin: 0,
                            jackpotCoinWin: 0,
                            jackpotCashWin: 0,
                            jackpotType: 0,
                        },
                    },
                ],
                nextCommands: [],
                nextCommandParams: [],
                playerState: {
                    public: {
                        curGameMod: "basic",
                        nextM: 0,
                        "@type":
                            "type.googleapis.com/sgc7pb.BasicPlayerPublicState",
                    },
                },
                finished: true,
                stake: null,
                playStartTime: 1722246598964,
            },
            playIndex: -1,
            bet: 100,
            lines: 50,
            totalwin: 1500,
            playwin: 0,
            maxWinLimit: 0,
        },
    };

    logic.onConfig(gamecfg, statedata, statelist);
    logic.setUIFrameworksFuncs(
        (wins) => {
            console.log(`${wins}`);
        },
        (curNum, totalNum) => {
            console.log(`${curNum} / ${totalNum}`);
        }
    );
    logic.addListener(async (gameResult2, step2, state2) => {
        console.log(gameResult2, step2, state2);

        if (step2.curStepIndex == 0) {
            expect(step2.lstStates.length).toBe(3);
        }
    });

    await logic.onMessage(msg).then(() => {
        console.log("Done!");
    });
});
